import type { Member } from "../models/member";

export const TeamMembers: Member[] = [
  {
    field: "FUNDRAISING",
    fname: "George",
    lname: "Angelakis",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/georgeangelakis",
  },
  {
    field: "FUNDRAISING",
    fname: "Christina",
    lname: "Chatzichrysou",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/christina-chatzichrysou-142464218/",
  },
  {
    field: "FUNDRAISING",
    fname: "Katerina",
    lname: "Zacharia",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "http://linkedin.com/in/αικατερίνη-ειρήνη-ζαχαρια-804600253",
  },
  {
    field: "DRY LAB",
    fname: "Isidoros",
    lname: "Chatzichrysos",
    info: "Computer Science Dept. University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/isidoros-chatzichrysos-187487204/",
  },
  {
    field: "DRY LAB",
    fname: "Babis",
    lname: "Digos",
    info: "Computer Science Dept., University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/babis-digos-5b8606203/",
  },
  {
    field: "WET LAB",
    fname: "Kiriakos",
    lname: "Mavridis",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "",
  },
  {
    field: "WET LAB",
    fname: "Ioli",
    lname: "Diamanti",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/apostolia-ioli-diamanti-9a78791ba",
  },
  {
    field: "WET LAB",
    fname: "Despoina",
    lname: "Lazaridou",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/despoina-lazaridou-4385b6253",
  },
  {
    field: "WET LAB",
    fname: "Aris",
    lname: "Logothetis",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/aris-logothetis-709b9a207",
  },
  {
    field: "SOCIAL",
    fname: "Sofia",
    lname: "Chatziavraam",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "",
  },
  {
    field: "HUMAN PRACTICES",
    fname: "Chrysianna",
    lname: "Psarologaki",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/chrysianna-psarologaki-965652253/",
  },
  {
    field: "HUMAN PRACTICES",
    fname: "Maria",
    lname: "Mpanou",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/maria-mpanou-867652253/",
  },
  {
    field: "HUMAN PRACTICES",
    fname: "Ioannis",
    lname: "Petrosian",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/ioannis-petrosian-3105a3253/",
  },
  {
    field: "TEAM LEADER",
    fname: "Sotiris",
    lname: "Marinos",
    info: "Biology Department, University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/sotiris-marinos-755644226",
  },
  {
    field: "TEAM ADVISOR",
    fname: "Stavros",
    lname: "Skrepetos",
    info: "Material Science & Technology Dept. University of Crete (UoC)",
    linkedIn: "https://www.linkedin.com/in/stavros-skrepetos-197092212",
  },
];
